### ISSUE TITLE
UnboundLocalError (archetype.py example with year of modernization 1994)

### ISSUE THREAD

**Issue by JSchiefelbein** [RWTH-EBC/TEASER#361]
The following error occurs (on development and master) when using 1994 as year of retrofit within
archetype.py

' prj.name = "ArchetypeBuildings_Retrofit"
  prj.retrofit_all_buildings(1994)
  prj.calc_all_buildings()'

Traceback (most recent call last):
  File "D:/Arbeitsordner_Lokal/PyCharm_workspace/TEASER/teaser/examples/archetype.py", line 126, in <module>
    example_type_building()
  File "D:/Arbeitsordner_Lokal/PyCharm_workspace/TEASER/teaser/examples/archetype.py", line 102, in example_type_building
    prj.retrofit_all_buildings(1994)
  File "d:\arbeitsordner_lokal\pycharm_workspace\teaser\teaser\project.py", line 191, in retrofit_all_buildings
    bldg.retrofit_building(year_of_retrofit, window_type, material)
  File "d:\arbeitsordner_lokal\pycharm_workspace\teaser\teaser\logic\buildingobjects\building.py", line 472, in retrofit_building
    zone.retrofit_zone(window_type, material)
  File "d:\arbeitsordner_lokal\pycharm_workspace\teaser\teaser\logic\buildingobjects\thermalzone.py", line 1302, in retrofit_zone
    wall_count.retrofit_wall(self.parent.year_of_retrofit, material)
  File "d:\arbeitsordner_lokal\pycharm_workspace\teaser\teaser\logic\buildingobjects\buildingphysics\wall.py", line 239, in retrofit_wall
    if self.ua_value < calc_u:
UnboundLocalError: local variable 'calc_u' referenced before assignment

**Comment by MichaMans** [comment]
This is a known limitation of the retrofit function. I admit that this will lead to an error which is not a good solution. we will change that to a warning and set the year of retrofit to 1995 since this is the oldest year of retrofit currently supported by teaser.

**Comment by JSchiefelbein** [comment]
Great, thanks for the info
